# Generated by Django 3.1.7 on 2021-04-01 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_delete_stuff'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='is_courier',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_courier',
            field=models.BooleanField(default=True),
        ),
    ]
