# Generated by Django 3.1.7 on 2021-04-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210401_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courier',
            name='is_courier',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_courier',
            field=models.BooleanField(default=False),
        ),
    ]
