# Generated by Django 3.1.7 on 2021-04-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210401_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='date',
        ),
        migrations.AddField(
            model_name='user',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата Рождения'),
        ),
    ]
