# Generated by Django 3.1.7 on 2021-04-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210401_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='user_avatar/', verbose_name='Аватарка'),
        ),
    ]
