# Generated by Django 3.1.7 on 2021-03-29 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('InStock', 'Order in stock'), ('OnWay', 'Order on way'), ('Delivered', 'Order delivered')], max_length=10)),
                ('quantity', models.IntegerField(verbose_name='количество продуктов')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=100000)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_courier', to='user.courier')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_customer', to='user.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_product', to='products.product')),
                ('stuff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_stuff', to='user.stuff')),
            ],
        ),
    ]
