# Generated by Django 3.1.7 on 2021-03-31 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('OnWay', 'Order on way'), ('Delivered', 'Order delivered')], max_length=10),
        ),
    ]
